[package]
name = "crypto_tracking"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
rand = "0.9.1"
ratatui = "0.29.0"
tokio = {version = "1.44.2", features = ["full"]}
